### ISSUE TITLE
Error while clearing cache after unzipping

### ISSUE THREAD

**Issue by jmoreno17** [hostnetbr/mautic-googleauthenticator#1]
Hi there! I downloaded the files, and unzipped in some instances of Mautic (v.2.12.1 and forward) and worked wonders, until I had to install it in older versions which prompted me with these error messages:

"The type hint of parameter "user_id" in method "setUserId" in class "Mautic
  Plugin\HostnetAuthBundle\Entity\AuthBrowser" is invalid."

"[ReflectionException]
  Class MauticPlugin\HostnetAuthBundle\Entity\int does not exist"

I thought at first it was due to the version, until today that happened on a 2.12.2 Mautic, tried to google the error but no luck, any help please? Thank you!

**Comment by henoliv** [comment]
Hi @ jmoreno17

First of all, thanks for the feedback, I hope the plugin is being useful.

I tried to reproduce the error but it's not happening in my attempts.

I updated the hints that might cause this problems in the AuthBrowser class, can you try it again?

If the problem persists, could you tell me the which older version you tried when it first occurred?

**Comment by jmoreno17** [comment]
Hi! First of all, thanks for the answer, I think yesterday we found out what made the error appear, it seems the Authenticator only works with php 7.+ and not all of our machines are, plus all of the instances in where the error appeared were php 5.6, can confirm this is the reason? 
Also, the plugin works wonders, keep up the good work!

**Comment by henoliv** [comment]
Bullseye. Yes, that's the reason.

We've developed the plugin targeting most recent php versions.

I will work on some instructions for a readme file, I think this will help prevent the same thing from happening to someone else.

Again, thanks for the feedback, it helps a lot.
