### ISSUE TITLE
How can I get this to work with Mautic 3?

### ISSUE THREAD

**Issue by Bogey** [hostnetbr/mautic-googleauthenticator#2]
Hi there, I love to see this working with Mautic 3. Unfortunately I can't find the cache folder to clear (it has changed location or is completely gone), so the authenticator never shows up in the plugins page. How can I get this to work with Mautic 3?
Cheers,
Erwin

**Comment by Bogey** [comment]
@henoliv 
Henrique, is there any intention of updating this plugin for Mautic 3?
Henrique, existe alguma intenção de atualizar este plugin para o Mautic 3?

**Comment by EmprendoHub** [comment]
I would also love to see this plugin updated to Mautic 3, if you can be so kind as to letting us know if you do intend to update code? and more or less by when? thank you so much

**Comment by henoliv** [comment]
Hi all,

I'm happy to see that this plugin is being helpful to you.

I got back to Mautic related projects recently.

I can't give you a precise date, but I'm currently working on updating these plugins. It shouldn't take long.

**Comment by Bogey** [comment]
Do you have something ready that we can test? ;)

**Comment by Bogey** [comment]
> Do you have something ready that we can test? ;)

Please?

**Comment by Bogey** [comment]
@henoliv Is it ready yet? 👍🏻

**Comment by matthiasexl** [comment]
Hi,
also really looking forward to an update :) 
Thank you for the great work,
Matt

**Comment by pedrodejesus** [comment]
Hi folks.

We just updated the repository with the changes for Mautic 3. Let us know if you find anything wrong :)
Best regards,
Pedro
